set_property PACKAGE_PIN N15 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
create_clock -period 10.000 [get_ports clk_100MHz]

# start here
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports vsync]
# set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports pclk]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports hsync]

set_property PACKAGE_PIN J15 [get_ports pclk]
set_property IOSTANDARD LVCMOS33 [get_ports pclk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pclk_IBUF]

set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports {data[0]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports {data[1]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports {data[2]}]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports {data[3]}]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS33} [get_ports {data[4]}]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports {data[5]}]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports {data[6]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {data[7]}]

set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVCMOS33} [get_ports pwdn]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports reset]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports xclk]
# end here
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid_left[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid_left[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid_left[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid_left[0]}]
set_property PACKAGE_PIN B3 [get_ports {hex_grid_left[3]}]
set_property PACKAGE_PIN C3 [get_ports {hex_grid_left[2]}]
set_property PACKAGE_PIN H6 [get_ports {hex_grid_left[1]}]
set_property PACKAGE_PIN G6 [get_ports {hex_grid_left[0]}]
set_property PACKAGE_PIN B5 [get_ports {hex_seg_left[7]}]
set_property PACKAGE_PIN C4 [get_ports {hex_seg_left[6]}]
set_property PACKAGE_PIN D6 [get_ports {hex_seg_left[5]}]
set_property PACKAGE_PIN D7 [get_ports {hex_seg_left[4]}]
set_property PACKAGE_PIN C5 [get_ports {hex_seg_left[3]}]
set_property PACKAGE_PIN D5 [get_ports {hex_seg_left[2]}]
set_property PACKAGE_PIN B4 [get_ports {hex_seg_left[1]}]
set_property PACKAGE_PIN E6 [get_ports {hex_seg_left[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_left[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_left[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_left[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_left[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_left[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_left[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_left[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg_left[0]}]

set_property -dict {PACKAGE_PIN E4 IOSTANDARD LVCMOS25} [get_ports {hex_grid_right[0]}]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS25} [get_ports {hex_grid_right[1]}]
set_property -dict {PACKAGE_PIN F5 IOSTANDARD LVCMOS25} [get_ports {hex_grid_right[2]}]
set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS25} [get_ports {hex_grid_right[3]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS25} [get_ports {hex_seg_right[0]}]
set_property -dict {PACKAGE_PIN G5 IOSTANDARD LVCMOS25} [get_ports {hex_seg_right[1]}]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS25} [get_ports {hex_seg_right[2]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS25} [get_ports {hex_seg_right[3]}]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS25} [get_ports {hex_seg_right[4]}]
set_property -dict {PACKAGE_PIN H3 IOSTANDARD LVCMOS25} [get_ports {hex_seg_right[5]}]
set_property -dict {PACKAGE_PIN E5 IOSTANDARD LVCMOS25} [get_ports {hex_seg_right[6]}]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS25} [get_ports {hex_seg_right[7]}]


set_property IOSTANDARD LVCMOS25 [get_ports btn_photo]
set_property IOSTANDARD LVCMOS25 [get_ports btn_read]
set_property IOSTANDARD LVCMOS25 [get_ports btn_test]

set_property PACKAGE_PIN G2 [get_ports btn_test]
set_property PACKAGE_PIN J2 [get_ports btn_photo]
set_property PACKAGE_PIN J1 [get_ports btn_read]


set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports {LED[0]}]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports {LED[1]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports {LED[2]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports {LED[3]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports {LED[4]}]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33} [get_ports {LED[5]}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports {LED[6]}]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33} [get_ports {LED[7]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports {LED[8]}]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports {LED[9]}]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33} [get_ports {LED[10]}]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports {LED[11]}]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports {LED[12]}]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports {LED[13]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports {LED[14]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {LED[15]}]